# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-slim

WORKDIR /app

# Install dependencies
COPY . /app
RUN pip install --no-cache-dir dmPython mcp pydantic

# Expose nothing specific; communicates over stdio

CMD ["python", "dameng/server.py"]
